// js/data.js
// =============================================================
// NovaHub Global Content Database
// =============================================================

const NOVAHUB_DATA = (() => {

  const categories = [
    { id: 'movies',      name: 'Movies & TV',         icon: '🍿', desc: 'Blockbusters, indie films, and binge-worthy series.' },
    { id: 'books',       name: 'Books',               icon: '📚', desc: 'Bestsellers, classics, and must-read literature.' },
    { id: 'ai-tools',   name: 'AI Tools',             icon: '✨', desc: 'Writing, image, video, and coding AI assistants.' },
    { id: 'productivity',name: 'Productivity',        icon: '⏳', desc: 'Focus apps, planners, notes, and time savers.' },
    { id: 'design',      name: 'Design & Coding',     icon: '🎨', desc: 'Visual design tools, editors, and dev utilities.' },
    { id: 'games',       name: 'Games',               icon: '🎮', desc: 'Browser games, console hits, and indie gems.' },
    { id: 'videos',      name: 'Videos & Tutorials',  icon: '🎬', desc: 'Learn anything — tech, life, and beyond.' },
  ];

  // ---- MOVIES -----------------------------------------------
  const movies = [
    { name: 'Dune: Part Two', genre: 'Sci-Fi / Epic', rating: 8.8, director: 'Denis Villeneuve', year: 2024, shortDesc: 'Paul Atreides unites with the Fremen to wage war against the Harkonnens.', fullDesc: 'Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.', image: 'https://images.unsplash.com/photo-1534809027769-b00d750a6bac?w=600&h=900&fit=crop', trailerUrl: 'https://www.youtube.com/embed/Way9Dexny3w', watchLink: 'https://www.amazon.com/Dune-Part-Two/dp/B0CWSQVGBF', trending: true, dailyPick: true },
    { name: 'Oppenheimer', genre: 'Biography / Drama', rating: 8.3, director: 'Christopher Nolan', year: 2023, shortDesc: 'The story of J. Robert Oppenheimer and the creation of the atomic bomb.', fullDesc: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.', image: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=600&h=900&fit=crop', trailerUrl: 'https://www.youtube.com/embed/uYPbbksJxIg', watchLink: 'https://www.peacocktv.com/watch/asset/movies/oppenheimer', trending: true },
    { name: 'Interstellar', genre: 'Sci-Fi / Adventure', rating: 8.7, director: 'Christopher Nolan', year: 2014, shortDesc: 'A team of explorers travel through a wormhole in space.', fullDesc: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.', image: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=600&h=900&fit=crop', trailerUrl: 'https://www.youtube.com/embed/zSWdZVtXT7E', watchLink: 'https://www.netflix.com/title/70305903' },
    { name: 'Deadpool & Wolverine', genre: 'Action / Comedy', rating: 7.8, director: 'Shawn Levy', year: 2024, shortDesc: 'Two unconventional heroes team up in the Marvel universe.', fullDesc: 'Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to help him in his mission.', image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=600&h=900&fit=crop', trailerUrl: 'https://www.youtube.com/embed/73_1biulkYk', watchLink: 'https://www.disneyplus.com', trending: true },
    { name: 'The Batman', genre: 'Action / Crime', rating: 7.9, director: 'Matt Reeves', year: 2022, shortDesc: 'Batman uncovers corruption in Gotham City.', fullDesc: 'When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city\'s hidden corruption.', image: 'https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=600&h=900&fit=crop', trailerUrl: 'https://www.youtube.com/embed/mqqft2x_Aa4', watchLink: 'https://www.hbomax.com' },
    { name: 'Parasite', genre: 'Thriller / Drama', rating: 8.5, director: 'Bong Joon-ho', year: 2019, shortDesc: 'A poor family schemes to become employed by a wealthy family.', fullDesc: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.', image: 'https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?w=600&h=900&fit=crop', trailerUrl: 'https://www.youtube.com/embed/5xH0HfJHsaY', watchLink: 'https://www.hulu.com' },
    { name: 'The Shawshank Redemption', genre: 'Drama', rating: 9.3, director: 'Frank Darabont', year: 1994, shortDesc: 'Two imprisoned men bond over years, finding solace and redemption through decency.', fullDesc: 'Over the course of several years, two imprisoned men bond through camaraderie, finding solace and eventual redemption through acts of common decency.', image: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=600&h=900&fit=crop', trailerUrl: 'https://www.youtube.com/embed/NmzuHjWmXOc', watchLink: 'https://www.netflix.com' },
    { name: 'Everything Everywhere All at Once', genre: 'Sci-Fi / Comedy', rating: 7.8, director: 'Daniels', year: 2022, shortDesc: 'A middle-aged Chinese immigrant is swept up in an insane adventure.', fullDesc: 'An aging Chinese immigrant is swept up in an insane adventure, where she alone can save the world by exploring other universes connecting with the lives she could have led.', image: 'https://images.unsplash.com/photo-1608889476518-738c9b1dcb40?w=600&h=900&fit=crop', trailerUrl: 'https://www.youtube.com/embed/wxN1T1uxQ2g', watchLink: 'https://www.amazon.com', trending: true },
    { name: 'Gladiator II', genre: 'Action / Epic', rating: 7.5, director: 'Ridley Scott', year: 2024, shortDesc: 'A new hero rises to battle the Roman empire.', fullDesc: 'Years after witnessing the death of revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered.', image: 'https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=600&h=900&fit=crop', trailerUrl: 'https://www.youtube.com/embed/2rBYzFh_oHA', watchLink: 'https://www.netflix.com' },
    { name: 'Avatar: The Way of Water', genre: 'Sci-Fi / Adventure', rating: 7.6, director: 'James Cameron', year: 2022, shortDesc: 'Jake Sully and Ney\'tiri must protect their family.', fullDesc: 'Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na\'vi race to protect their home.', image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&h=900&fit=crop', trailerUrl: 'https://www.youtube.com/embed/a8Gx8wiNbs8', watchLink: 'https://www.disneyplus.com' },
    { name: 'Top Gun: Maverick', genre: 'Action / Drama', rating: 8.3, director: 'Joseph Kosinski', year: 2022, shortDesc: 'After thirty years, Maverick is back training the best of the best.', fullDesc: 'After more than thirty years of service as one of the Navy\'s top aviators, Pete Mitchell is where he belongs, pushing the envelope as a courageous test pilot.', image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=600&h=900&fit=crop', trailerUrl: 'https://www.youtube.com/embed/giXco2jaZ_4', watchLink: 'https://www.netflix.com', trending: true },
    { name: 'Alien: Romulus', genre: 'Sci-Fi / Horror', rating: 7.3, director: 'Fede Álvarez', year: 2024, shortDesc: 'A group of colonists face the galaxy\'s most terrifying lifeform.', fullDesc: 'A group of young people find themselves in a confrontation with the most terrifying life form in the universe while scavenging the deep ends of a derelict space station.', image: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=600&h=900&fit=crop', trailerUrl: 'https://www.youtube.com/embed/aPoKsVHHEAM', watchLink: 'https://www.hulu.com' },
  ];

  // ---- BOOKS ------------------------------------------------
  const books = [
    { name: 'Atomic Habits', author: 'James Clear', genre: 'Self-Help', rating: 4.8, summary: 'An easy and proven way to build good habits and break bad ones.', fullDesc: 'No matter your goals, Atomic Habits offers a proven framework for improving every day. James Clear reveals practical strategies that will teach you how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.', image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&h=900&fit=crop', buyLink: 'https://www.amazon.com/Atomic-Habits-Proven-Build-Break/dp/0735211299', embedId: 'ItHdUpsyAa0C', trending: true, dailyPick: true },
    { name: 'The Psychology of Money', author: 'Morgan Housel', genre: 'Finance', rating: 4.7, summary: 'Timeless lessons on wealth, greed, and happiness.', fullDesc: 'Doing well with money isn\'t necessarily about what you know. It\'s about how you behave. And behavior is hard to teach, even to really smart people.', image: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=600&h=900&fit=crop', buyLink: 'https://www.amazon.com/Psychology-Money-Timeless-lessons-happiness/dp/0857197681', embedId: 'l2XVEAAAQBAJ', trending: true },
    { name: 'Deep Work', author: 'Cal Newport', genre: 'Self-Help / Career', rating: 4.6, summary: 'Rules for focused success in a distracted world.', fullDesc: 'Deep work is the ability to focus without distraction on a cognitively demanding task. It\'s a skill that allows you to quickly master complicated information and produce better results in less time.', image: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600&h=900&fit=crop', buyLink: 'https://www.amazon.com/Deep-Work-Focused-Success-Distracted/dp/1455586692', embedId: 'CUFMACJAHSoC' },
    { name: 'Thinking, Fast and Slow', author: 'Daniel Kahneman', genre: 'Psychology', rating: 4.6, summary: 'How two systems of thought shape judgments and decisions.', fullDesc: 'In the international bestseller, Daniel Kahneman explains the two systems that drive the way we think: System 1 is fast, intuitive, and emotional; System 2 is slower, more deliberative, and more logical.', image: 'https://images.unsplash.com/photo-1448932284983-0c7b152eba33?w=600&h=900&fit=crop', buyLink: 'https://www.amazon.com/Thinking-Fast-Slow-Daniel-Kahneman/dp/0374533555', embedId: 'bRpn-zsnCMYC' },
    { name: 'The Lean Startup', author: 'Eric Ries', genre: 'Business', rating: 4.5, summary: 'How constant innovation creates radically successful businesses.', fullDesc: 'The Lean Startup approach fosters companies that are both more capital efficient and that leverage human creativity more effectively.', image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&h=900&fit=crop', buyLink: 'https://www.amazon.com/Lean-Startup-Entrepreneurs-Continuous-Innovation/dp/0307887898', trending: true },
    { name: '1984', author: 'George Orwell', genre: 'Dystopian Fiction', rating: 4.7, summary: 'A harrowing vision of a totalitarian society and the individual\'s last stand.', fullDesc: 'Among the seminal texts of the 20th century, 1984 is a rare work that grows more haunting as its futuristic purgatory becomes more of a real possibility.', image: 'https://images.unsplash.com/photo-1495640388908-05fa85288e61?w=600&h=900&fit=crop', buyLink: 'https://www.amazon.com/1984-Signet-Classics-George-Orwell/dp/0451524934' },
    { name: 'The Alchemist', author: 'Paulo Coelho', genre: 'Fiction / Philosophy', rating: 4.6, summary: 'A timeless fable of following your dreams.', fullDesc: 'A young Andalusian shepherd who yearns to travel in search of a worldly treasure as extravagant as any ever found. The story of the treasures he finds along the way teaches us, as well as Santiago, about the essential wisdom of listening to our hearts.', image: 'https://images.unsplash.com/photo-1491841550275-ad7854e35ca6?w=600&h=900&fit=crop', buyLink: 'https://www.amazon.com/Alchemist-Paulo-Coelho/dp/0062315005', dailyPick: true },
    { name: 'Zero to One', author: 'Peter Thiel', genre: 'Business / Entrepreneurship', rating: 4.5, summary: 'Notes on startups, or how to build the future.', fullDesc: 'The next Bill Gates will not build an operating system. The next Larry Page or Sergey Brin won\'t make a search engine. If you are copying these guys, you aren\'t learning from them. It\'s easier to copy a model than to make something new: going from 1 to n adds more of what the world already has.', image: 'https://images.unsplash.com/paper-notebooks-r-BsCOqczepDw?w=600&h=900&fit=crop', buyLink: 'https://www.amazon.com/Zero-One-Notes-Startups-Future/dp/0804139296' },
    { name: 'Can\'t Hurt Me', author: 'David Goggins', genre: 'Memoir / Self-Help', rating: 4.8, summary: 'Master your mind and defy the odds.', fullDesc: 'For David Goggins, childhood was a nightmare — poverty, prejudice, and physical abuse colored his days and haunted his nights. But through self-discipline, mental toughness, and hard work, Goggins transformed himself from a depressed, overweight young man into a U.S. Armed Forces icon.', image: 'https://images.unsplash.com/photo-1581579186913-45ac3e6efe93?w=600&h=900&fit=crop', buyLink: 'https://www.amazon.com/Cant-Hurt-Me-Master-Your/dp/1544512287', trending: true },
    { name: 'Atomic Habits (Spanish)', author: 'James Clear', genre: 'Auto-Ayuda', rating: 4.8, summary: 'Hábitos Atómicos: Una manera sencilla de cambiar rutinas y alcanzar grandes metas.', fullDesc: 'Spanish edition of Atomic Habits, the international bestseller on building better habits.', image: 'https://images.unsplash.com/photo-1474932430478-367dbb6832c1?w=600&h=900&fit=crop', buyLink: 'https://www.amazon.com/H%C3%A1bitos-At%C3%B3micos-Paperback/dp/6073196512' },
    { name: 'The Great Gatsby', author: 'F. Scott Fitzgerald', genre: 'Classic Fiction', rating: 4.1, summary: 'Jazz Age excess, mystery, and the unattainable green light.', fullDesc: 'The story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, of lavish parties on Long Island at a time when The New York Times noted "gin was the national drink and sex the national obsession."', image: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600&h=900&fit=crop', buyLink: 'https://www.amazon.com/Great-Gatsby-F-Scott-Fitzgerald/dp/0743273567' },
    { name: 'Sapiens', author: 'Yuval Noah Harari', genre: 'History / Science', rating: 4.4, summary: 'A brief history of humankind, from savanna to civilization.', fullDesc: 'A groundbreaking narrative of humanity\'s creation and evolution. 100,000 years ago, at least six human species inhabited the earth. Today there is just one. Us. How did our species succeed in the battle for dominance?', image: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=600&h=900&fit=crop', buyLink: 'https://www.amazon.com/Sapiens-Humankind-Yuval-Noah-Harari/dp/0062316095', trending: true },
  ];

  // ---- AI TOOLS -----------------------------------------------
  const aiTools = [
    { name: 'ChatGPT', pricing: 'Free / $20/mo', category: 'Writing AI', shortDesc: 'The world\'s most popular conversational AI assistant.', fullDesc: 'ChatGPT is a large language model by OpenAI capable of generating human-quality text, answering questions, writing code, and holding multi-turn conversations.', pros: ['Best in class reasoning', 'Wide knowledge base', 'Plugins and DALL-E integration'], cons: ['Knowledge cutoff', 'Can hallucinate', 'Free tier has limits'], bestFor: 'Everyone who writes, researches, codes, or communicates professionally.', affiliateLink: 'https://chat.openai.com', embedId: 'text-ai', trending: true, dailyPick: true },
    { name: 'Midjourney', pricing: 'Paid from $10/mo', category: 'Image AI', shortDesc: 'Stunning AI image generation via Discord & web.', fullDesc: 'Midjourney generates extraordinarily detailed and artistic images from simple text prompts. Known for its cinematic quality and artistic style.', pros: ['Incredible output quality', 'Massive community', 'Diverse art styles'], cons: ['Requires Discord', 'No free tier permanently', 'Slow at peak times'], bestFor: 'Designers, artists, content creators, and marketers.', affiliateLink: 'https://www.midjourney.com', embedId: 'image-ai', trending: true },
    { name: 'Claude', pricing: 'Free / $20/mo', category: 'Writing AI', shortDesc: 'Anthropic\'s highly capable and safety-focused AI assistant.', fullDesc: 'Claude by Anthropic excels at long-form content, nuanced analysis, and coding. It has a huge 200k token context window and is preferred for creative writing.', pros: ['Large context window', 'Nuanced and safe', 'Excellent at writing'], cons: ['Less plugin ecosystem', 'Slower API rollout'], bestFor: 'Professionals who need long-form analysis, reports, or creative content.', affiliateLink: 'https://claude.ai', embedId: 'text-ai', trending: true },
    { name: 'Gemini', pricing: 'Free / $20/mo', category: 'Writing AI', shortDesc: 'Google\'s flagship multimodal AI assistant.', fullDesc: 'Google Gemini (formerly Bard) integrates with Google Workspace, Gmail, and Docs. Gemini Advanced uses the Ultra model for complex reasoning.', pros: ['Google integration', 'Multimodal (text+images)', 'Real-time search'], cons: ['Less popular than ChatGPT', 'Safety refusals'], bestFor: 'Google Workspace users who want AI inside Docs, Gmail, and Sheets.', affiliateLink: 'https://gemini.google.com', embedId: 'text-ai' },
    { name: 'Stable Diffusion', pricing: 'Free', category: 'Image AI', shortDesc: 'Open source AI image generation you can run locally.', fullDesc: 'Stable Diffusion is a free, open-source text-to-image model that can be run on your own hardware. Massive community ecosystem with thousands of custom models and styles.', pros: ['Completely free', 'Runs locally', 'Limitless with custom models'], cons: ['Needs a GPU', 'Complex setup', 'Inconsistent quality'], bestFor: 'Developers, power users, and creatives wanting unlimited image generation.', affiliateLink: 'https://stability.ai', embedId: 'image-ai', dailyPick: true },
    { name: 'ElevenLabs', pricing: 'Free / $5/mo', category: 'Audio AI', shortDesc: 'Ultra-realistic AI voice cloning and text-to-speech.', fullDesc: 'ElevenLabs offers the most realistic AI voices on the market. It can clone any voice from a short audio clip and generate nuanced, emotional speech.', pros: ['Exceptional realism', 'Voice cloning', 'Multi-language'], cons: ['Free tier limited API calls', 'Ethical misuse potential'], bestFor: 'Podcasters, audiobook creators, YouTube content creators, and e-learning teams.', affiliateLink: 'https://elevenlabs.io' },
    { name: 'RunwayML', pricing: 'Free / $15/mo', category: 'Video AI', shortDesc: 'AI-powered video generation, editing, and effects.', fullDesc: 'RunwayML is the leading AI video platform, offering Gen-2 text-to-video generation, background removal, motion tracking, and more. Used by major film studios.', pros: ['Text-to-video generation', 'Professional-grade tools', 'Browser-based'], cons: ['Expensive credits', 'Video length limits'], bestFor: 'Filmmakers, video editors, social media creators, and marketing teams.', affiliateLink: 'https://runwayml.com', trending: true },
    { name: 'Perplexity AI', pricing: 'Free / $20/mo', category: 'Research AI', shortDesc: 'AI-powered real-time search and research assistant.', fullDesc: 'Perplexity AI is an AI-based search engine that provides AI-generated responses with live citations from the web. It\'s become the go-to tool for quick, cited research.', pros: ['Real-time web search', 'Cited sources', 'Conversational search'], cons: ['Answers can miss nuance', 'Pro needed for best results'], bestFor: 'Students, journalists, researchers, and knowledge workers.', affiliateLink: 'https://www.perplexity.ai', trending: true },
    { name: 'GitHub Copilot', pricing: 'Paid $10/mo', category: 'Coding AI', shortDesc: 'AI pair programmer right inside your code editor.', fullDesc: 'GitHub Copilot uses OpenAI Codex to suggest code and functions in real-time, directly in your IDE. It supports 20+ programming languages and is used by millions of developers.', pros: ['Deep IDE integration', 'Multi-language', 'Explains code'], cons: ['Paid subscription', 'Suggestions can be wrong', 'Privacy concerns'], bestFor: 'Software developers, data scientists, and coding bootcamp students.', affiliateLink: 'https://github.com/features/copilot' },
    { name: 'Suno AI', pricing: 'Free / $10/mo', category: 'Music AI', shortDesc: 'Create full songs with vocals from a simple text prompt.', fullDesc: 'Suno AI lets you generate complete songs — including vocals, lyrics, and instrumentation — from just a text description. Supports any genre or style.', pros: ['Full music generation', 'Very fast', 'Free tier available'], cons: ['Less control over style', 'Cannot export stems'], bestFor: 'Content creators, marketers, indie musicians, and anyone needing background music fast.', affiliateLink: 'https://suno.ai', dailyPick: true },
    { name: 'DALL-E 3', pricing: 'Free (with ChatGPT)', category: 'Image AI', shortDesc: 'OpenAI\'s flagship image generation model.', fullDesc: 'DALL-E 3 generates highly realistic and detailed images from natural language prompts. Available directly through ChatGPT Plus and the API.', pros: ['Integrated with ChatGPT', 'Excellent at following prompts', 'Photorealistic option'], cons: ['Conservative content policy', 'Paid access only for API'], bestFor: 'ChatGPT Plus subscribers needing quick, high-quality image assets.', affiliateLink: 'https://openai.com/dall-e-3', embedId: 'image-ai', trending: true },
    { name: 'Notion AI', pricing: '$10/mo add-on', category: 'Productivity AI', shortDesc: 'AI that writes, edits, and summarizes inside Notion.', fullDesc: 'Notion AI brings the power of generative AI directly into your Notion workspace. Ask it to write, summarize, fix grammar, or brainstorm — all in context with your existing docs.', pros: ['Integrated with Notion', 'Great for team knowledge bases', 'Summarization'], cons: ['Requires Notion subscription', 'Limited standalone value'], bestFor: 'Teams already using Notion for project management and documentation.', affiliateLink: 'https://www.notion.so/product/ai' },
  ];

  // ---- PRODUCTIVITY -----------------------------------------------
  const productivityTools = [
    { name: 'Notion', pricing: 'Free / $10/mo', shortDesc: 'All-in-one workspace for notes, wikis, and project management.', fullDesc: 'Notion is an all-in-one workspace where you can write, plan, collaborate and get organized. It\'s used by millions of students, freelancers, and teams worldwide.', pros: ['Extremely customizable', 'Great for teams', 'Databases and Kanban'], cons: ['Steep learning curve', 'Can be slow on mobile'], bestFor: 'Teams, students, and knowledge workers craving one place for everything.', affiliateLink: 'https://www.notion.so', embedId: 'markdown', trending: true, dailyPick: true },
    { name: 'Obsidian', pricing: 'Free / $50 license', shortDesc: 'Private markdown notes with a powerful knowledge graph.', fullDesc: 'Obsidian is a powerful and extensible knowledge base that works on top of a local folder of plain text Markdown files. Your notes are stored locally, entirely under your control.', pros: ['Fully offline', 'Plugin ecosystem', 'Knowledge graph'], cons: ['No native collaboration', 'Desktop-focused'], bestFor: 'Writers, researchers, and students who value local-first data ownership.', affiliateLink: 'https://obsidian.md', embedId: 'markdown' },
    { name: 'Pomofocus', pricing: 'Free', shortDesc: 'Elegant browser-based Pomodoro timer.', fullDesc: 'Pomofocus is a customizable Pomodoro timer that works on desktop & mobile browser. The aim is to help you focus on any task you are working on, such as study, writing, or coding.', pros: ['Clean UI', 'Free forever', 'Task list built in'], cons: ['Browser only', 'No sync'], bestFor: 'Students and focused workers using the Pomodoro technique.', affiliateLink: 'https://pomofocus.io', embedId: 'timer', trending: true },
    { name: 'Todoist', pricing: 'Free / $4/mo', shortDesc: 'The most popular task manager with natural language input.', fullDesc: 'Todoist is the world\'s most popular task manager. Its natural language processing lets you type "Meeting tomorrow at 3 PM" and it schedules it automatically.', pros: ['Natural language date parsing', 'Cross-platform', 'Google Calendar sync'], cons: ['Best templates behind paywall', 'Limited free recurring tasks'], bestFor: 'Individuals and teams who want the simplest path from idea to task.', affiliateLink: 'https://todoist.com', dailyPick: true },
    { name: 'Toggl Track', pricing: 'Free', shortDesc: 'The easiest time tracker for freelancers and teams.', fullDesc: 'Toggl Track is a simple online time tracking tool that lets you track the time you spend on different tasks and projects. It\'s essential for billing and productivity analysis.', pros: ['Very simple to use', 'Detailed reports', 'Browser extension'], cons: ['Invoicing requires premium', 'Limited free reports'], bestFor: 'Freelancers and agencies who need to track billable hours.', affiliateLink: 'https://toggl.com' },
    { name: 'Google Calendar', pricing: 'Free', shortDesc: 'The world\'s most used calendar, now with Gemini AI.', fullDesc: 'Google Calendar is a free time management and scheduling service. It integrates with Gmail, Meet, Drive, and now includes Gemini AI for smart scheduling.', pros: ['Free forever', 'Google integration', 'Shared calendars'], cons: ['Privacy concerns', 'Limited customization'], bestFor: 'Anyone in the Google ecosystem who needs seamless scheduling.', affiliateLink: 'https://calendar.google.com' },
    { name: 'Linear', pricing: 'Free / $8/mo', shortDesc: 'The issue tracker built for modern software teams.', fullDesc: 'Linear is the tool of choice for high-performance software teams. It\'s fast, keyboard-first, and has beautiful animations and workflows that replace Jira for many teams.', pros: ['Blazing fast', 'Beautiful UI', 'Git integrations'], cons: ['Software teams only', 'Smaller community than Jira'], bestFor: 'Engineering teams who want Jira-like power with a consumer-grade experience.', affiliateLink: 'https://linear.app', trending: true },
    { name: 'Readwise', pricing: '$7.99/mo', shortDesc: 'Resurface and remember what you read.', fullDesc: 'Readwise helps you get more out of what you read by syncing your book highlights and sending you a daily review email. It integrates with Kindle, Instapaper, Pocket, and more.', pros: ['Sync all highlights', 'Spaced repetition', 'Reader app included'], cons: ['Paid subscription only', 'Best on e-readers'], bestFor: 'Avid readers and life-long learners who want to retain more knowledge.', affiliateLink: 'https://readwise.io' },
  ];

  // ---- DESIGN & CODING -----------------------------------------------
  const designTools = [
    { name: 'Figma', pricing: 'Free / $12/mo', shortDesc: 'The collaborative interface design and prototyping tool.', fullDesc: 'Figma is a web-based design tool that has become the industry standard for UI/UX. Real-time collaboration means your entire team can design together, in the browser.', pros: ['Real-time collaboration', 'Free for personal use', 'Massive component libraries'], cons: ['Offline needs desktop app', 'Resource intensive'], bestFor: 'Product designers, UI/UX teams, and anyone building digital products.', affiliateLink: 'https://figma.com', trending: true, dailyPick: true },
    { name: 'VS Code', pricing: 'Free', shortDesc: 'The world\'s most popular code editor by Microsoft.', fullDesc: 'Visual Studio Code is a free, open-source code editor with built-in Git integration, an extension marketplace with thousands of plugins, and excellent debugging tools.', pros: ['Free and open source', '30k+ extensions', 'Integrated terminal'], cons: ['Can be heavy with extensions', 'Not a full IDE'], bestFor: 'Software developers working in any language from JavaScript to Python.', affiliateLink: 'https://code.visualstudio.com', embedId: 'sandbox' },
    { name: 'Canva', pricing: 'Free / $12.99/mo', shortDesc: 'Drag-and-drop design for non-designers.', fullDesc: 'Canva makes it shockingly easy to create social media posts, presentations, posters, videos, logos, and more. It has thousands of templates and now has AI features.', pros: ['Beginner friendly', 'Huge template library', 'Magic AI tools', 'Web-based'], cons: ['Less precision than Figma', 'Pro features paywalled'], bestFor: 'Social media managers, small business owners, and non-designers.', affiliateLink: 'https://www.canva.com', trending: true },
    { name: 'CodePen', pricing: 'Free / $8/mo', shortDesc: 'Online code editor and front-end development playground.', fullDesc: 'CodePen is a social development environment for front-end designers and developers. Build and deploy a website, show off your work, build test cases, and find inspiration.', pros: ['Instant HTML/CSS/JS preview', 'Huge community', 'Great for demos'], cons: ['Not for backend code', 'Free tier is public'], bestFor: 'Web developers who want to learn, experiment, and share code demos.', affiliateLink: 'https://codepen.io', embedId: 'sandbox', dailyPick: true },
    { name: 'Framer', pricing: 'Free / $10/mo', shortDesc: 'Design and publish production-quality websites without code.', fullDesc: 'Framer is the fast and fun way to build your site. Generate a site from an AI prompt, design it with Figma-like tools, and publish live instantly.', pros: ['No-code + code hybrid', 'AI site generation', 'Production-ready sites'], cons: ['Less design control than Figma', 'Monthly fee for custom domains'], bestFor: 'Agencies, startups, and freelancers who want a premium website without a developer.', affiliateLink: 'https://framer.com' },
    { name: 'Vercel', pricing: 'Free / $20/mo', shortDesc: 'The platform for frontend developers to ship globally fast.', fullDesc: 'Vercel is the platform where the world\'s leading software companies deploy their frontend apps. Zero configuration, instant deployments, and AI-powered analytics.', pros: ['Instant CI/CD', 'Free hobby tier', 'Edge network globally'], cons: ['Serverless only for backend', 'Cost at scale'], bestFor: 'Frontend developers deploying Next.js, React, Svelte, and static sites.', affiliateLink: 'https://vercel.com', trending: true },
    { name: 'Tailwind CSS', pricing: 'Free', shortDesc: 'A utility-first CSS framework for rapidly building custom UIs.', fullDesc: 'Tailwind CSS is a utility-first CSS framework packed with classes like flex, pt-4, text-center, and rotate-90 that can be composed to build any design, directly in your markup.', pros: ['Extremely fast development', 'Highly customizable', 'No unused CSS in prod'], cons: ['Learning curve', 'HTML gets verbose'], bestFor: 'Web developers who want to rapidly build custom UIs without leaving HTML.', affiliateLink: 'https://tailwindcss.com', embedId: 'sandbox' },
    { name: 'Dribbble', pricing: 'Free / $5/mo', shortDesc: 'The world\'s leading community for creative professionals.', fullDesc: 'Dribbble is the leading destination to find and showcase creative work and home to the world\'s best design professionals.', pros: ['Huge design inspiration', 'Job board', 'Portfolio hosting'], cons: ['Invite-only for posting', 'Jobs require Pro plan'], bestFor: 'Designers looking for inspiration, community, and career opportunities.', affiliateLink: 'https://dribbble.com' },
  ];

  // ---- GAMES -----------------------------------------------
  const games = [
    { name: 'Baldur\'s Gate 3', genre: 'RPG', rating: 9.5, developer: 'Larian Studios', platforms: 'PC, PS5, Xbox', shortDesc: 'The most acclaimed RPG of the decade. Gather your party, venture into Faerûn.', fullDesc: 'Baldur\'s Gate 3 is a story-rich, party-based RPG set in the universe of Dungeons & Dragons, where your choices shape a tale of fellowship and betrayal.', image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&h=900&fit=crop', trailerUrl: 'https://www.youtube.com/embed/1T8rYtI8XjM', playLink: 'https://store.steampowered.com/app/1086940/Baldurs_Gate_3/', trending: true, dailyPick: true },
    { name: 'Elden Ring', genre: 'Action RPG', rating: 9.4, developer: 'FromSoftware', platforms: 'PC, PS5, Xbox', shortDesc: 'An expansive open world soulslike from FromSoftware and George R.R. Martin.', fullDesc: 'THE NEW FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.', image: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=600&h=900&fit=crop', trailerUrl: 'https://www.youtube.com/embed/qFUf8HMFAdY', playLink: 'https://store.steampowered.com/app/1245620/ELDEN_RING/', trending: true },
    { name: 'The Legend of Zelda: TOTK', genre: 'Adventure', rating: 9.0, developer: 'Nintendo', platforms: 'Nintendo Switch', shortDesc: 'Link ventures into the skies above Hyrule in this breathtaking adventure.', fullDesc: 'An epic adventure across the land and skies of Hyrule awaits in The Legend of Zelda: Tears of the Kingdom. The ancient mystery surrounding the kingdom of Hyrule has been reignited.', image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&h=900&fit=crop', trailerUrl: 'https://www.youtube.com/embed/uHGShqcAHlQ', playLink: 'https://www.nintendo.com', trending: true },
    { name: 'Red Dead Redemption 2', genre: 'Open World / Action', rating: 9.7, developer: 'Rockstar Games', platforms: 'PC, PS4, Xbox', shortDesc: 'An epic tale of life in America\'s unforgiving heartland.', fullDesc: 'America, 1899. The end of the wild west era has begun. After a robbery goes badly wrong in the western town of Blackwater, Arthur Morgan and the Van der Linde gang are forced to flee.', image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&h=900&fit=crop', trailerUrl: 'https://www.youtube.com/embed/gmA6MrX81z4', playLink: 'https://www.rockstargames.com/reddeadredemption2/' },
    { name: 'Cyberpunk 2077', genre: 'Action RPG', rating: 8.8, developer: 'CD Projekt Red', platforms: 'PC, PS5, Xbox', shortDesc: 'An open-world action RPG in the mega-city Night City.', fullDesc: 'Cyberpunk 2077 is an open-world, action-adventure RPG set in the megalopolis of Night City, where you play as a cyberpunk mercenary wrapped up in a do-or-die fight for survival.', image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=600&h=900&fit=crop', trailerUrl: 'https://www.youtube.com/embed/qIcTM8WXFjk', playLink: 'https://www.cyberpunk.net', trending: true },
    { name: 'Hollow Knight', genre: 'Metroidvania', rating: 9.2, developer: 'Team Cherry', platforms: 'PC, Switch, PS, Xbox', shortDesc: 'A challenging 2D action adventure through a vast underground kingdom.', fullDesc: 'Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom of insects and heroes. Explore twisting caverns, battle tainted creatures and befriend bizarre bugs.', image: 'https://images.unsplash.com/photo-1569098644584-210bcd375b59?w=600&h=900&fit=crop', trailerUrl: 'https://www.youtube.com/embed/UAO2urG23S4', playLink: 'https://store.steampowered.com/app/367520/Hollow_Knight/', dailyPick: true },
    { name: 'Minecraft', genre: 'Sandbox / Survival', rating: 9.0, developer: 'Mojang', platforms: 'All Platforms', shortDesc: 'The best-selling video game of all time. Build, explore, survive.', fullDesc: 'Minecraft is a game about placing blocks and going on adventures. Explore randomly generated worlds and build amazing things from the simplest of homes to the grandest of castles. Play in creative mode with unlimited resources or mine deep into the world in survival mode.', image: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=600&h=900&fit=crop', trailerUrl: 'https://www.youtube.com/embed/MmB9b5njVbA', playLink: 'https://www.minecraft.net' },
    { name: 'Stardew Valley', genre: 'Simulation / RPG', rating: 9.4, developer: 'ConcernedApe', platforms: 'PC, Switch, PS, Xbox', shortDesc: 'Escape to the countryside and build the farm of your dreams.', fullDesc: 'A charming and enchanting experience that celebrates rural life and the joy of growing your own fruits and vegetables while forging friendships with the town\'s residents.', image: 'https://images.unsplash.com/photo-1484910292437-025e5d13ce87?w=600&h=900&fit=crop', playLink: 'https://www.stardewvalley.net', trending: true },
  ];

  // ---- VIDEOS / TUTORIALS -----------------------------------------------
  const videos = [
    { name: 'Fireship: 100 Days to Learn React', category: 'Web Dev', platform: 'YouTube', shortDesc: 'Essential React concepts distilled into bitesize videos.', embedId: 'b9eMGE7QtTk', link: 'https://www.youtube.com/@Fireship', image: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=600&h=400&fit=crop', trending: true },
    { name: 'Andrej Karpathy: Intro to Neural Networks', category: 'AI / ML', platform: 'YouTube', shortDesc: 'Build a neural network from scratch with the ex-Tesla AI Director.', embedId: 'VMj-3S1tku0', link: 'https://www.youtube.com/@AndrejKarpathy', image: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&h=400&fit=crop', trending: true, dailyPick: true },
    { name: '3Blue1Brown: Essence of Calculus', category: 'Math', platform: 'YouTube', shortDesc: 'Visual, intuitive explanations of the fundamentals of calculus.', embedId: 'WUvTyaaNkzM', link: 'https://www.youtube.com/@3blue1brown', image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&h=400&fit=crop' },
    { name: 'Lex Fridman: Sam Altman Interview', category: 'AI / Tech', platform: 'YouTube', shortDesc: 'The OpenAI CEO discusses AGI, safety, and the future of AI.', embedId: 'jvqFAi7vkBc', link: 'https://www.youtube.com/@lexfridman', image: 'https://images.unsplash.com/photo-1535378917042-10a22c65bb84?w=600&h=400&fit=crop', trending: true },
    { name: 'Traversy Media: CSS Crash Course', category: 'Web Dev', platform: 'YouTube', shortDesc: 'Get up to speed on modern CSS in 90 minutes.', embedId: 'yfoY53QXEnI', link: 'https://www.youtube.com/@TraversyMedia', image: 'https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?w=600&h=400&fit=crop' },
    { name: 'TED: The Secret to Living Longer', category: 'Health & Science', platform: 'TED', shortDesc: 'Susan Pinker on why face-to-face contact is fundamental.', embedId: 'WT5GGjvVYFM', link: 'https://www.ted.com', image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&h=400&fit=crop', dailyPick: true },
    { name: 'Ali Abdaal: How to Build a Second Brain', category: 'Productivity', platform: 'YouTube', shortDesc: 'Practical guide to knowledge management and personal productivity.', embedId: 'K-ssUVyfsnA', link: 'https://www.youtube.com/@aliabdaal', image: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=600&h=400&fit=crop', trending: true },
    { name: 'Kurzgesagt: Are You Vaccinated?', category: 'Science', platform: 'YouTube', shortDesc: 'Beautifully animated scientific explainer on vaccines.', embedId: 'a6bMb1pRgxM', link: 'https://www.youtube.com/@kurzgesagt', image: 'https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?w=600&h=400&fit=crop' },
    { name: 'MKBHD: Apple Vision Pro Review', category: 'Tech', platform: 'YouTube', shortDesc: 'The definitive review of Apple\'s spatial computing headset.', embedId: 'dQw4w9WgXcQ', link: 'https://www.youtube.com/@mkbhd', image: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=600&h=400&fit=crop', trending: true, dailyPick: true },
  ];

  // ---- BLOG POSTS -----------------------------------------------
  const blogPosts = [
    { id: 'future-of-discovery', title: 'Why NovaHub is the Future of Content Discovery', excerpt: 'The internet is drowning in content. We built NovaHub to be the antidote — a beautiful, curated, AI-powered lens on everything worth your time.', date: 'Oct 15, 2026', author: 'The NovaHub Team', image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=400&fit=crop', category: 'Platform' },
    { id: 'best-ai-tools-2026', title: 'The 10 Best AI Tools to Use in 2026', excerpt: 'From AI writing assistants to image generators and music composers — we cover the best tools that are changing how humans create and work.', date: 'Oct 10, 2026', author: 'NovaHub Editors', image: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&h=400&fit=crop', category: 'AI Tools' },
    { id: 'top-movies-october-2026', title: 'October 2026\'s Most Anticipated Movies', excerpt: 'From sci-fi spectacles to intimate dramas, October has an incredible lineup. Our editors break down the must-watch films and where to stream them.', date: 'Oct 1, 2026', author: 'Film Desk', image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&h=400&fit=crop', category: 'Movies' },
    { id: 'productivity-guide-2026', title: 'The Ultimate Productivity Stack for 2026', excerpt: 'Pairing Notion, Todoist, Toggl, and AI assistants — the definitive productivity toolkit for professionals who mean business.', date: 'Sep 25, 2026', author: 'Work Smarter Desk', image: 'https://images.unsplash.com/photo-1507925921893-ce482cb4afff?w=800&h=400&fit=crop', category: 'Productivity' },
    { id: 'best-books-of-year', title: '20 Books That Will Change How You Think', excerpt: 'A carefully curated list from Atomic Habits to Sapiens — books that our editors and community agree deserve a place on every bookshelf.', date: 'Sep 18, 2026', author: 'Book Club Desk', image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&h=400&fit=crop', category: 'Books' },
  ];

  // ---- BUILDER FUNCTIONS -----------------------------------------------
  const buildItem = (rawItem, type, categoryId) => {
    const id = (rawItem.name || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
    return { ...rawItem, id, type, categoryId };
  };


  // ---- NEWS ITEMS ------------------------------------------------
  const newsItems = [
    { id:'n1', title:'OpenAI Announces GPT-5: Largest Model Yet', summary:'OpenAI unveiled GPT-5 with unprecedented reasoning ability, multimodal input support, and real-time web browsing built in. Early benchmarks beat all previous models by a wide margin.', tag:'AI', source:'The Verge', date:'2026-03-20', image:'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&h=340&fit=crop', url:'#' },
    { id:'n2', title:'Google DeepMind\'s Gemini Ultra 2 Launches Globally', summary:'Google\'s most powerful AI model is now available worldwide. Gemini Ultra 2 supports 2M token context and natively integrates with Google Workspace, Search, and YouTube.', tag:'AI', source:'TechCrunch', date:'2026-03-19', image:'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=600&h=340&fit=crop', url:'#' },
    { id:'n3', title:'Meta Releases Open-Source AI Video Generator', summary:'Meta\'s new video generation model, freely available on GitHub, can produce 60-second photorealistic clips from text prompts. Creators are already building short films with it.', tag:'Tech', source:'Wired', date:'2026-03-18', image:'https://images.unsplash.com/photo-1535016120720-40c646be5580?w=600&h=340&fit=crop', url:'#' },
    { id:'n4', title:'Apple Vision Pro 2 Leaks Reveal Lighter Design', summary:'Leaked CAD renders show Apple Vision Pro 2 with a dramatically lighter titanium frame, improved battery life, and a new gesture interface. Expected to launch at WWDC 2026.', tag:'Tech', source:'MacRumors', date:'2026-03-17', image:'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=600&h=340&fit=crop', url:'#' },
    { id:'n5', title:'Baldur\'s Gate 3 Story DLC Officially Confirmed', summary:'Larian Studios confirmed a major story expansion for Baldur\'s Gate 3, bringing a new character origin, two new cities, and an extended epilogue. No release date announced yet.', tag:'Gaming', source:'IGN', date:'2026-03-16', image:'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&h=340&fit=crop', url:'#' },
    { id:'n6', title:'The Psychology of Money Hits 10 Million Copies Sold', summary:'Morgan Housel\'s personal finance masterpiece has officially crossed 10 million copies worldwide, cementing its place as one of the best-selling business books of the decade.', tag:'Books', source:'Publishers Weekly', date:'2026-03-15', image:'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=600&h=340&fit=crop', url:'#' },
    { id:'n7', title:'Figma Acquires Spline 3D for $200M', summary:'Figma announced the acquisition of Spline, the popular browser-based 3D design tool, bringing three-dimensional design capabilities directly into Figma\'s interface.', tag:'Design', source:'Design Week', date:'2026-03-14', image:'https://images.unsplash.com/photo-1558655146-d09347e92766?w=600&h=340&fit=crop', url:'#' },
    { id:'n8', title:'New Study: AI Doubles Developer Productivity', summary:'A Stanford study of 5,000 developers found that those using AI coding assistants (GitHub Copilot, Cursor) completed tasks 2.1x faster with a 40% reduction in bug rates.', tag:'AI', source:'Stanford HAI', date:'2026-03-13', image:'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=600&h=340&fit=crop', url:'#' },
    { id:'n9', title:'Notion Raises $500M at $20B Valuation', summary:'Notion secured a $500M Series D round led by Sequoia Capital, valuing the company at $20 billion. The funds will go toward AI features and global expansion.', tag:'Productivity', source:'Bloomberg', date:'2026-03-12', image:'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&h=340&fit=crop', url:'#' },
    { id:'n10', title:'RunwayML Gen-3 Produces Hollywood-Quality Video', summary:'The latest generation of RunwayML\'s text-to-video model produces 4K video clips indistinguishable from professional footage. Used on three major studio productions already.', tag:'AI', source:'Variety', date:'2026-03-11', image:'https://images.unsplash.com/photo-1536240478700-b869ad10e128?w=600&h=340&fit=crop', url:'#' },
    { id:'n11', title:'Steam Breaks 40 Million Concurrent Users Record', summary:'Valve\'s Steam platform set a new all-time peak of 40.2 million concurrent users, driven by the launch of multiple AAA titles and the indie gaming renaissance.', tag:'Gaming', source:'PC Gamer', date:'2026-03-10', image:'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&h=340&fit=crop', url:'#' },
    { id:'n12', title:'ElevenLabs Voice API Now Free for Indie Developers', summary:'ElevenLabs announced a generous free tier for independent developers, offering 100,000 characters per month — enough for a full audiobook chapter — at no cost.', tag:'AI', source:'ElevenLabs Blog', date:'2026-03-09', image:'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=600&h=340&fit=crop', url:'#' },
  ];

  // ---- SEEDED COMMENTS (demo data) --------------------------------
  const comments = {
    'dune-part-two': [
      { id:'c001', author:'CuriousOwl42', text:'Absolutely breathtaking cinematography. Denis Villeneuve is a genius — the sandworm riding scene alone is worth it.', timestamp: Date.now() - 3600000 * 5, likes: 14, likedBy:[] },
      { id:'c002', author:'BoldFox7', text:'Best sci-fi movie since 2001: A Space Odyssey. The score by Hans Zimmer is haunting and beautiful.', timestamp: Date.now() - 3600000 * 12, likes: 8, likedBy:[] },
    ],
    'atomic-habits': [
      { id:'c003', author:'BraveHawk23', text:'This book literally changed my life. Started waking up at 6am after reading the identity chapter.', timestamp: Date.now() - 86400000, likes: 22, likedBy:[] },
      { id:'c004', author:'WildPanda88', text:'James Clear makes habit formation feel genuinely achievable. Already built 3 new habits in 3 weeks.', timestamp: Date.now() - 86400000 * 2, likes: 11, likedBy:[] },
    ],
    'chatgpt': [
      { id:'c005', author:'CleverBear19', text:'GPT-4o is insane for writing. I use it every single day for blog posts, emails, and code reviews.', timestamp: Date.now() - 86400000 * 3, likes: 31, likedBy:[] },
    ],
    "baldur-s-gate-3": [
      { id:'c006', author:'SharpEagle55', text:'The most complete RPG ever made. 300 hours in and still finding new routes. Absolute masterpiece.', timestamp: Date.now() - 86400000, likes: 27, likedBy:[] },
    ],
    'figma': [
      { id:'c007', author:'WittyLion3', text:'Figma\'s dev mode alone is worth the price. Our design-to-code handoff used to take days, now it takes hours.', timestamp: Date.now() - 3600000 * 8, likes: 18, likedBy:[] },
    ],
  };

  const allItems = [
    ...movies.map(m => buildItem(m, 'movie', 'movies')),
    ...books.map(b => buildItem(b, 'book', 'books')),
    ...aiTools.map(t => buildItem(t, 'tool', 'ai-tools')),
    ...productivityTools.map(t => buildItem(t, 'tool', 'productivity')),
    ...designTools.map(t => buildItem(t, 'tool', 'design')),
    ...games.map(g => buildItem(g, 'game', 'games')),
    ...videos.map(v => buildItem(v, 'video', 'videos')),
  ];

  return { categories, items: allItems, blogPosts, newsItems, comments };
})();

